# TCL File Generated by Component Editor 11.1sp1
# Wed Feb 22 07:35:02 CET 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | nios_interface_shift_leds "nios_interface_shift_leds" v1.0
# | JM 2012.02.22.07:35:02
# | Interface_Shift_Leds_green
# | 
# | M:/Altera_VHDL/ETTI4_Applications/DE0_CycloneIII_Eval_Board/Version_1_0/Source/nios_interface_shift_leds.vhd
# | 
# |    ./nios_interface_shift_leds.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module nios_interface_shift_leds
# | 
set_module_property DESCRIPTION Interface_Shift_Leds_green
set_module_property NAME nios_interface_shift_leds
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ETTI4
set_module_property AUTHOR JM
set_module_property DISPLAY_NAME nios_interface_shift_leds
set_module_property TOP_LEVEL_HDL_FILE nios_interface_shift_leds.vhd
set_module_property TOP_LEVEL_HDL_MODULE nios_interface_shift_leds
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME nios_interface_shift_leds
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file nios_interface_shift_leds.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 ce_n chipselect_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 write_data writedata Input 32
add_interface_port avalon_slave_0 read_data readdata Output 32
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 reg_addr address Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end LEDG_SER_DATA export Output 1
add_interface_port conduit_end LEDG_SER_CLK export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink CLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges BOTH

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink RESET_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------
